name: staging-infra-deploy

on:
  push:
    branches:
      - main

jobs:
  staging-infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      # Best practice: use a short-lived to auth to Pulumi Cloud
      # The OIDC Issuer must be properly configured in the Pulumi Organization
      # For more information, see 
      # https://www.pulumi.com/docs/pulumi-cloud/oidc/client/github/

      - name: setup pulumi cloud access
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi-sandbox-diana
          requested-token-type: urn:pulumi:token-type:access_token:organization

      - name: preview infra
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: pulumi-sandbox-diana/buzz/staging
          work-dir: ./infra
          # (optional) A GitHub token that has access levels
          # to allow the Action to comment on a PR. 
          github-token: ${{ github.token }}
          comment-on-pr: true
          comment-on-summary: true
          edit-pr-comment: true